---
- hosts: all
  become: yes
  tasks:
    - name: Include CloudHelper
      include_role:
        name: geometrylabs.cloud_helper
      vars:
        enable_cloud_wait: true
        enable_jq: true
    - name: Run volumes playbook
      include_role:
        name: volumes
      when: instance_store_enabled | default(false) | bool
    - name: Run OS hardening playbook
      include_role:
        name: dev-sec.os-hardening
      when: ansible_hardening | default(false) | bool
    - name: Run SSH hardening playbook
      include_role:
        name: dev-sec.ssh-hardening
      when: ansible_hardening | default(false) | bool
    - name: Install Polkadot Base
      include_role:
        name: geometrylabs.polkadot_base
      vars:
        prometheus_port: "{{ item.value['polkadot_prometheus'] }}"
        api_rpc_port: "{{ item.value['json_rpc'] }}"
        api_wss_port: "{{ item.value['ws_rpc'] }}"
        health_check_port: "{{ item.value['api_health'] }}"
        chain: "{{ item.value['name'] }}"
      loop: "{{ network_settings | from_json | dict2items }}"
    - name: Install Polkadot Library
      include_role:
        name: geometrylabs.polkadot_library
      vars:
        prometheus_port: "{{ item.value['polkadot_prometheus'] }}"
        api_rpc_port: "{{ item.value['json_rpc'] }}"
        api_wss_port: "{{ item.value['ws_rpc'] }}"
        chain_stub: "{{ item.value['shortname'] }}"
        chain: "{{ item.value['name'] }}"
        project: "{{ item.value['name'] }}"
      loop: "{{ network_settings | from_json | dict2items }}"