---
collections:
  - name: devsec.hardening
    version: 7.6.0

roles:
  - src: geometrylabs.cloud_helper

  - src: geometrylabs.polkadot_base

  - src: geometrylabs.polkadot_library

  - src: geometrylabs.polkadot_truth

  - src: geometrylabs.polkadot_validator

  - name: ansible-consul
    src: https://github.com/geometry-labs/ansible-consul.git
    scm: git
    version: master

  - name: envoyproxy
    src: fabiocruzcoelho.envoyproxy
