---
- hosts: all
  become: yes
  tasks:
    - name: Include CloudHelper
      include_role:
        name: insight_infra.cloud_helper
      vars:
        enable_cloud_wait: true
        enable_jq: true
    - name: Run volumes playbook
      include_role:
        name: volumes
      when: instance_store_enabled | default(false) | bool
    - name: Run OS hardening playbook
      include_role:
        name: dev-sec.os-hardening
      when: ansible_hardening | default(false) | bool
    - name: Run SSH hardening playbook
      include_role:
        name: dev-sec.ssh-hardening
      when: ansible_hardening | default(false) | bool
    - name: Install Polkadot Base
      include_role:
        name: insight_w3f.polkadot_base
    - name: Install Polkadot Validator
      include_role:
        name: insight_w3f.polkadot_validator