name: Integration Tests

on: push

jobs:
  go-tests:
    name: Run Terratest Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Download Go Modules
        run: go mod download
        working-directory: test

      - uses: autero1/action-terraform@v1.0.0
        with:
          terraform_version: 0.12.21
      - name: Run Go Tests
        run: make test
        working-directory: test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}

      - uses: autero1/action-terraform@v1.0.0
        with:
          terraform_version: 0.14.6
      - name: Run Go Tests
        run: make test
        working-directory: test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
