name: Integration Tests

on: push

jobs:
  go-tests:
    name: Run Terratest Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Download Go Modules
        run: go mod download

      - uses: autero1/action-terraform@v1.0.0
        with:
          terraform_version: 0.13.5
      - name: Run tests - TF13
        run: make test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}

      - uses: autero1/action-terraform@v1.0.0
        with:
          terraform_version: 0.14.10
      - name: Run Go Tests
        run: make test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
